import type { Recipe } from "./recipes.types.js";

export const recipes: Recipe[] = [
  {
    id: 1,
    name: "Chicken Pasta",
    imageUrl: "https://images.example.com/chicken-pasta.jpg",
    cuisine: "Italian",
    difficulty: "Easy",
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    caloriesPerServing: 520,
    rating: 4.6,
    reviewCount: 120,
    ingredients: ["chicken breast", "pasta", "tomato sauce", "garlic", "olive oil"],
    instructions: ["Cook pasta.", "Sauté chicken with garlic.", "Combine and serve."],
    tags: ["pasta", "chicken", "quick"],
    mealTypes: ["dinner"],
  },
  {
    id: 2,
    name: "Beef Tacos",
    imageUrl: "https://images.example.com/beef-tacos.jpg",
    cuisine: "Mexican",
    difficulty: "Easy",
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 6,
    caloriesPerServing: 380,
    rating: 4.4,
    reviewCount: 89,
    ingredients: ["ground beef", "taco shells", "onion", "cumin", "cheddar cheese"],
    instructions: ["Season and cook beef.", "Warm taco shells.", "Assemble tacos."],
    tags: ["tacos", "beef", "family"],
    mealTypes: ["lunch", "dinner"],
  },
  {
    id: 3,
    name: "Vegetable Stir Fry",
    imageUrl: "https://images.example.com/vegetable-stir-fry.jpg",
    cuisine: "Asian",
    difficulty: "Easy",
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 3,
    caloriesPerServing: 210,
    rating: 4.2,
    reviewCount: 56,
    ingredients: ["broccoli", "bell pepper", "soy sauce", "ginger", "rice"],
    instructions: ["Prep vegetables.", "Stir fry over high heat.", "Serve with rice."],
    tags: ["vegetarian", "healthy", "quick"],
    mealTypes: ["lunch", "dinner"],
  },
  {
    id: 4,
    name: "Classic Margherita Pizza",
    imageUrl: "https://images.example.com/margherita-pizza.jpg",
    cuisine: "Italian",
    difficulty: "Medium",
    prepTimeMinutes: 30,
    cookTimeMinutes: 15,
    servings: 4,
    caloriesPerServing: 640,
    rating: 4.8,
    reviewCount: 203,
    ingredients: ["pizza dough", "tomato sauce", "mozzarella", "fresh basil", "olive oil"],
    instructions: ["Stretch dough.", "Add sauce and cheese.", "Bake until golden."],
    tags: ["pizza", "italian", "classic"],
    mealTypes: ["lunch", "dinner"],
  },
  {
    id: 5,
    name: "Salmon with Lemon Butter",
    imageUrl: "https://images.example.com/salmon-lemon.jpg",
    cuisine: "American",
    difficulty: "Medium",
    prepTimeMinutes: 10,
    cookTimeMinutes: 18,
    servings: 2,
    caloriesPerServing: 450,
    rating: 4.7,
    reviewCount: 142,
    ingredients: ["salmon fillet", "butter", "lemon", "dill", "salt"],
    instructions: ["Season salmon.", "Pan sear until crisp.", "Finish with lemon butter."],
    tags: ["seafood", "healthy", "gluten-free"],
    mealTypes: ["dinner"],
  },
  {
    id: 6,
    name: "Chicken Caesar Salad",
    imageUrl: "https://images.example.com/chicken-caesar.jpg",
    cuisine: "American",
    difficulty: "Easy",
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 2,
    caloriesPerServing: 320,
    rating: 4.3,
    reviewCount: 74,
    ingredients: ["romaine lettuce", "chicken breast", "caesar dressing", "parmesan", "croutons"],
    instructions: ["Grill chicken.", "Toss lettuce with dressing.", "Top with chicken and parmesan."],
    tags: ["salad", "chicken", "light"],
    mealTypes: ["lunch"],
  },
  {
    id: 7,
    name: "Beef Bourguignon",
    imageUrl: "https://images.example.com/beef-bourguignon.jpg",
    cuisine: "French",
    difficulty: "Hard",
    prepTimeMinutes: 45,
    cookTimeMinutes: 180,
    servings: 6,
    caloriesPerServing: 580,
    rating: 4.9,
    reviewCount: 167,
    ingredients: ["beef chuck", "red wine", "onion", "carrot", "mushrooms"],
    instructions: ["Sear beef.", "Simmer with wine and vegetables.", "Serve with potatoes."],
    tags: ["beef", "slow-cook", "classic"],
    mealTypes: ["dinner"],
  },
  {
    id: 8,
    name: "Mushroom Risotto",
    imageUrl: "https://images.example.com/mushroom-risotto.jpg",
    cuisine: "Italian",
    difficulty: "Medium",
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 4,
    caloriesPerServing: 490,
    rating: 4.5,
    reviewCount: 98,
    ingredients: ["arborio rice", "mushrooms", "parmesan", "white wine", "butter"],
    instructions: ["Sauté mushrooms.", "Add rice and wine gradually.", "Stir until creamy."],
    tags: ["risotto", "vegetarian", "comfort"],
    mealTypes: ["dinner"],
  },
  {
    id: 9,
    name: "Thai Green Curry",
    imageUrl: "https://images.example.com/thai-green-curry.jpg",
    cuisine: "Thai",
    difficulty: "Medium",
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 4,
    caloriesPerServing: 410,
    rating: 4.6,
    reviewCount: 111,
    ingredients: ["chicken thigh", "green curry paste", "coconut milk", "bamboo shoots", "basil"],
    instructions: ["Fry curry paste.", "Add coconut milk and chicken.", "Simmer and garnish."],
    tags: ["curry", "spicy", "asian"],
    mealTypes: ["lunch", "dinner"],
  },
  {
    id: 10,
    name: "Greek Yogurt Parfait",
    imageUrl: "https://images.example.com/yogurt-parfait.jpg",
    cuisine: "Greek",
    difficulty: "Easy",
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    caloriesPerServing: 180,
    rating: 4.1,
    reviewCount: 42,
    ingredients: ["greek yogurt", "honey", "granola", "berries", "mint"],
    instructions: ["Layer yogurt and granola.", "Top with berries and honey."],
    tags: ["breakfast", "healthy", "quick"],
    mealTypes: ["breakfast", "snack"],
  },
  {
    id: 11,
    name: "Spaghetti Carbonara",
    imageUrl: "https://images.example.com/spaghetti-carbonara.jpg",
    cuisine: "Italian",
    difficulty: "Medium",
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    caloriesPerServing: 610,
    rating: 4.7,
    reviewCount: 156,
    ingredients: ["spaghetti", "eggs", "pancetta", "parmesan", "black pepper"],
    instructions: ["Cook pasta.", "Crisp pancetta.", "Toss with egg and cheese off heat."],
    tags: ["pasta", "italian", "classic"],
    mealTypes: ["lunch", "dinner"],
  },
  {
    id: 12,
    name: "Chicken Tikka Masala",
    imageUrl: "https://images.example.com/chicken-tikka-masala.jpg",
    cuisine: "Indian",
    difficulty: "Medium",
    prepTimeMinutes: 25,
    cookTimeMinutes: 30,
    servings: 5,
    caloriesPerServing: 540,
    rating: 4.8,
    reviewCount: 189,
    ingredients: ["chicken breast", "yogurt", "tomato puree", "garam masala", "cream"],
    instructions: ["Marinate chicken.", "Grill and simmer in sauce.", "Serve with rice."],
    tags: ["curry", "chicken", "indian"],
    mealTypes: ["dinner"],
  },
  {
    id: 13,
    name: "Avocado Toast",
    imageUrl: "https://images.example.com/avocado-toast.jpg",
    cuisine: "American",
    difficulty: "Easy",
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    caloriesPerServing: 250,
    rating: 4.0,
    reviewCount: 35,
    ingredients: ["sourdough bread", "avocado", "lemon", "salt", "chili flakes"],
    instructions: ["Toast bread.", "Mash avocado with lemon.", "Spread and season."],
    tags: ["breakfast", "vegetarian", "quick"],
    mealTypes: ["breakfast", "snack"],
  },
  {
    id: 14,
    name: "Lamb Kebabs",
    imageUrl: "https://images.example.com/lamb-kebabs.jpg",
    cuisine: "Middle Eastern",
    difficulty: "Medium",
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    caloriesPerServing: 470,
    rating: 4.5,
    reviewCount: 67,
    ingredients: ["lamb shoulder", "cumin", "paprika", "onion", "yogurt"],
    instructions: ["Marinate lamb.", "Skewer and grill.", "Serve with flatbread."],
    tags: ["grill", "lamb", "spicy"],
    mealTypes: ["dinner"],
  },
];
